name: Build

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        game_version: ["official"]
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download SDK
        run: |
            $sdk_link = "https://drive.usercontent.google.com/download?id=1RsjLS5CUi5DJctWNi6T7Bo88pJurpik6&authuser=0&confirm=t&uuid=90ee5b05-60f8-485a-9381-2fdab22fa64f&at=ALoNOgmU9X45PBhZrO7xtZEUsaK0%3A1747208924976"
            $output = "sdk.zip"
            Invoke-WebRequest -Uri $sdk_link -OutFile $output -MaximumRedirection 0
            Expand-Archive -Path sdk.zip -DestinationPath CppSDK -Force

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v2

      - uses: lukka/get-cmake@latest

      - name: Configure TOF-SIH
        run: cmake -B build -S . 

      - name: Build TOF-SIH
        run: cmake --build build --config Release

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TOFInternal-${{ matrix.game_version }}
          path: |
            build/bin/Release/TOFInternal.dll
            build/bin/Release/injector.exe
            build/bin/Release/_aux.dll

      - name: Extract tag name
        if: startsWith(github.ref, 'refs/tags/')
        id: tag
        shell: bash
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Zip build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $zipFile = "TOFInternal-${{ matrix.game_version }}.zip"
          Compress-Archive -Path "build/bin/Release/TOFInternal.dll", "build/bin/Release/injector.exe", "build/bin/Release/_aux.dll" -DestinationPath $zipFile -Force

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag.outputs.TAG_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: TOFInternal-${{ matrix.game_version }}.zip
